services:
  db:
    image: mariadb:11.4
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: sfp
      MARIADB_USER: sfp
      MARIADB_PASSWORD: sfp
    volumes:
      - sfp_db_data:/var/lib/mysql
      - ./docker/init:/docker-entrypoint-initdb.d:ro
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

volumes:
  sfp_db_data:
