export const ledgerCopy = {
  quickAdd: 'Registrar movimiento',
  quickAddTitle: 'Registro rápido',
  quickAddTooltip: 'Atajo N',
  saved: 'Movimiento guardado',
  noTransactions: 'Aún no hay movimientos',
  noTransactionsHint: 'Registra tu primer ingreso o gasto.',
  noAccounts: 'No tienes cuentas',
  noAccountsHint: 'Crea una cuenta para empezar a registrar movimientos.',
  accountArchived: 'Cuenta archivada',
  createAccount: 'Nueva cuenta',
  createTransaction: 'Nuevo movimiento',
  invalidTransfer: 'La transferencia requiere cuenta origen y destino distintas',
  amountPositive: 'El monto debe ser mayor que cero',
} as const;
